attempt at refactoring the code to modules

diff --git a/test/usr/bin/nsbootd b/test/usr/bin/nsbootd
--- a/test/usr/bin/nsbootd
+++ b/test/usr/bin/nsbootd
@@ -1,91 +1,184 @@
-#!/usr/bin/lua
+#!/bin/sh
+
+### BEGIN INIT INFO
+# Provides:	  nginx
+# Required-Start:    $local_fs $remote_fs $network $syslog $named
+# Required-Stop:     $local_fs $remote_fs $network $syslog $named
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts the nginx web server
+# Description:       starts nginx using start-stop-daemon
+### END INIT INFO
+
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/bin/nsbootd
+NAME=nsbootd
+DESC=nsbootd
+
+# Include nginx defaults if available
+
+STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
+
+test -x $DAEMON || exit 0
+
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
+
+# Try to extract nginx pidfile
+PID=/run/${NAME}.pid
+if [ -z "$PID" ]; then
+	PID=/run/${NAME}.pid
+fi
+
+if [ -n "$ULIMIT" ]; then
+	# Set ulimit if it is set in /etc/default/nginx
+	ulimit $ULIMIT
+fi
+
+start_nsbootd() {
+	# Start the daemon/service
+	#
+	# Returns:
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start -b --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start -b --quiet --pidfile $PID --exec $DAEMON -- \
+		$DAEMON_OPTS 2>/dev/null \
+		|| return 2
+}
 
 
--- local socket = require("socket")
--- socket.unix = require"socket.unix"
--- local server = assert(socket.bind("*", 51515))
--- local tcp = assert(socket.tcp())
+stop_nsbootd() {
+	# Stops the daemon/service
+	#
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+	RETVAL="$?"
+	sleep 1
+	return "$RETVAL"
+}
+
+reload_nsbootd() {
+	# Function that sends a SIGHUP to the daemon/service
+	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
+	return 0
+}
 
 
--- function testpid (p_input)
--- local posix = require "posix"
--- local pid = posix.fork()
-
--- if pid == 0 then 
---   -- this is the child process
---   print(posix.getpid('pid') .. ": child process")
--- 	if p_input ~= nil and os.execute(p_input) then return "true\n" else return "false\n" end
--- else 
---   -- this is the parent process
---   print(posix.getpid('pid') .. ": parent process")
-
---   -- wait for the child process to finish
---   posix.wait(pid) 
-
--- end
--- end;
-
--- print(socket._VERSION)
--- print(tcp)
-
--- while 1 do
-
---   local client = server:accept()
-
---   line = client:receive()
---   print(line)
---   testpid(line)
--- 	client:send("RESULT: ")
-  
---   client:close();
-
--- end
-local posix = require "posix"
-local SOCKET="/tmp/socket_nsboot"
--- Server code
-function StartServerSocket()
-	local libsocket = require "socket"
-	local libunix = require "socket.unix"
-	local socket = assert(libunix())
-
-	assert(socket:bind(SOCKET))
-	assert(socket:listen())
-	conn = assert(socket:accept())
-	while 1 do
-	    data=conn:receive()
-
-	   if data ~= nil then
-	   	 print(data) 
-	-- local pid = posix.fork()
-		-- if pid == 0 then 
-		   if os.execute(data) then 
-		   	print("Got line: " .. data)
-		   	conn:send("echo: " .. data .. "\n")
-		   else
-		   	conn:send("FALSE")
-		   end;
-		   conn:close()
-
-		   
-		   break
+upgrade_nsbootd() {
+	# Online upgrade nginx executable
+	# http://nginx.org/en/docs/control.html
+	#
+	# Return
+	#   0 if nginx has been successfully upgraded
+	#   1 if nginx is not running
+	#   2 if the pid files were not created on time
+	#   3 if the old master could not be killed
+	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
+		# Wait for both old and new master to write their pid file
+		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
+			cnt=`expr $cnt + 1`
+			if [ $cnt -gt 10 ]; then
+				return 2
+			fi
+			sleep 1
+		done
+		# Everything is ready, gracefully stop the old master
+		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
+			return 0
 		else
-		   	conn:send("FALSE")
-		   	conn:close()
-		end;
-		    os.remove(SOCKET)
-	  		-- print(posix.getpid('pid') .. ": child process")
-	-- else 
-	--   print(posix.getpid('pid') .. ": parent process")
-	-- 	   	conn:send("false fork")
-	-- 	   	conn:close()
-	--   posix.wait(pid)
-	end;
-end;
+			return 3
+		fi
+	else
+		return 1
+	fi
+}
 
-while true do
-	io.open("/run/nsbootd.pid", "w"):write(require("posix").getpid().pid):close()
-	os.remove(SOCKET)
+case "$1" in
+	start)
+		log_daemon_msg "Starting $DESC" "$NAME"
+		start_nsbootd
+		case "$?" in
+			0|1) log_end_msg 0 ;;
+			2)   log_end_msg 1 ;;
+		esac
+		;;
+	stop)
+		log_daemon_msg "Stopping $DESC" "$NAME"
+		stop_nsbootd
+		case "$?" in
+			0|1) log_end_msg 0 ;;
+			2)   log_end_msg 1 ;;
+		esac
+		;;
+	restart)
+		log_daemon_msg "Restarting $DESC" "$NAME"
 
-	StartServerSocket()
-	print("RESTART SERVER ....")
-end;
+		# Check configuration before stopping nginx
+		if ! test_config; then
+			log_end_msg 1 # Configuration error
+			exit $?
+		fi
+
+		stop_nsbootd
+		case "$?" in
+			0|1)
+				start_nginx
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+				;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+				;;
+		esac
+		;;
+	reload|force-reload)
+		log_daemon_msg "Reloading $DESC configuration" "$NAME"
+
+		# Check configuration before stopping nginx
+		#
+		# This is not entirely correct since the on-disk nginx binary
+		# may differ from the in-memory one, but that's not common.
+		# We prefer to check the configuration and return an error
+		# to the administrator.
+		if ! test_config; then
+			log_end_msg 1 # Configuration error
+			exit $?
+		fi
+
+		reload_nsbootd
+		log_end_msg $?
+		;;
+	configtest|testconfig)
+		log_daemon_msg "Testing $DESC configuration"
+		test_config
+		log_end_msg $?
+		;;
+	status)
+		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
+	upgrade)
+		log_daemon_msg "Upgrading binary" "$NAME"
+		upgrade_nginx
+		log_end_msg $?
+		;;
+	rotate)
+		log_daemon_msg "Re-opening $DESC log files" "$NAME"
+		rotate_logs
+		log_end_msg $?
+		;;
+	*)
+		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
+		exit 3
+		;;
+esac
